### ISSUE TITLE
rglobi now on cran

### ISSUE THREAD

**Issue by jhpoelen** [ropensci/ropensci.github.com#5]
Hi!

Just wanted to let you know that rglobi is now available through [CRAN](http://cran.r-project.org/web/packages/rglobi/) . . . let me know how I can help update the current entry of rglobi on ropensci.org : 

![screen shot 2015-04-11 at 8 36 22 am](https://cloud.githubusercontent.com/assets/1084872/7101981/9c9972d8-e026-11e4-9d32-d324a76afada.png)

**Comment by sckott** [comment]
thanks @jhpoelen -updated on the website , see https://ropensci.org/packages/#rglobi
